replicaCount: 1

image:
  repository: ghcr.io/lolvveryz/template
  tag: latest
  pullPolicy: IfNotPresent
  
imagePullSecrets:
  - name: ghcr-secret
  
service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  host: django.local

postgresql:
  enabled: true
  auth:
    username: "user"
    password: "password"
    database: "mydb"

redis:
  enabled: true
  auth:
    enabled: false

env:
  DJANGO_SETTINGS_MODULE: "djangoSite.settings"
  DEBUG: "False"
