name: CI / Build & Package

on:
  push:
    branches:
      - main

permissions:
  contents: write       
  packages: write

env:
  IMAGE_NAME: my-django-app
  CHART_DIR: my-django-chart
  CHART_PACKAGE_DIR: charts-output
  CHART_NAME: my-django-chart
  CHART_VERSION: 0.1.0

jobs:
  build-and-publish:
    name: Build & Publish Docker image + Package Helm chart
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # -------------------- Docker image --------------------
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry (Docker)
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Build and push Docker image
      id: build-image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
          ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

    # -------------------- Helm chart --------------------
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.13.0

    - name: Update Helm dependencies
      run: helm dependency update "${{ env.CHART_DIR }}"

    - name: Package Helm chart
      id: package_chart
      run: |
        mkdir -p ${{ env.CHART_PACKAGE_DIR }}
        helm package "${{ env.CHART_DIR }}" \
          --destination "${{ env.CHART_PACKAGE_DIR }}" \
          --version "${{ env.CHART_VERSION }}" \
          --app-version "${{ github.sha }}"
        PACKAGE=$(ls ${{ env.CHART_PACKAGE_DIR }}/*.tgz | head -n 1)
        echo "chart_path=$PACKAGE" >> $GITHUB_OUTPUT

    - name: Upload packaged chart as artifact
      uses: actions/upload-artifact@v4
      with:
        name: packaged-chart
        path: ${{ env.CHART_PACKAGE_DIR }}

    # -------------------- GHCR push (Helm) --------------------
    - name: Login to GHCR (Helm)
      run: |
        helm registry login ghcr.io -u ${{ github.actor }} -p ${{ secrets.TOKEN }}

    - name: Push Helm chart to GHCR
      run: |
        helm push ${{ env.CHART_PACKAGE_DIR }}/${{ env.CHART_NAME }}-${{ env.CHART_VERSION }}.tgz \
          oci://ghcr.io/${{ github.repository_owner }}/helm/${{ env.CHART_NAME }}

    # -------------------- Release --------------------
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "chart-${{ github.sha }}"
        name: "Helm chart package for ${{ github.sha }}"
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Upload chart to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.package_chart.outputs.chart_path }}
        asset_name: ${{ env.CHART_NAME }}-${{ env.CHART_VERSION }}.tgz
        asset_content_type: application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
