name: CI / Build & Package

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/template
  CHART_DIR: my-django-chart
  CHART_PACKAGE_DIR: charts-output
  CHART_NAME: my-django-chart
  CHART_VERSION: 0.1.0

jobs:
  build-and-publish:
    name: Build & Publish Docker image + Package Helm chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # -------------------- Docker image --------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      # -------------------- Helm chart --------------------
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.0

      - name: Update Helm dependencies
        run: helm dependency update "${{ env.CHART_DIR }}"

      - name: Package Helm chart
        id: package_chart
        run: |
          mkdir -p ${{ env.CHART_PACKAGE_DIR }}
          helm package "${{ env.CHART_DIR }}" \
            --destination "${{ env.CHART_PACKAGE_DIR }}" \
            --version "${{ env.CHART_VERSION }}" \
            --app-version "${{ github.sha }}"
          echo "chart_path=$(ls ${{ env.CHART_PACKAGE_DIR }}/*.tgz | head -n 1)" >> $GITHUB_OUTPUT

      # -------------------- Push Helm chart to GHCR --------------------
      - name: Log in to GHCR (Helm)
        run: echo ${{ secrets.TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Helm chart to GHCR
        run: |
          helm push ${{ steps.package_chart.outputs.chart_path }} \
            oci://ghcr.io/${{ github.repository_owner }}/helm

      # -------------------- Create GitHub Release --------------------
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "chart-${{ github.sha }}"
          name: "Helm chart for commit ${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload chart to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.package_chart.outputs.chart_path }}
          asset_name: ${{ env.CHART_NAME }}-${{ env.CHART_VERSION }}.tgz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
